WebShop/Controllers/CatagoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebShop.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace WebShop.Controllers
{
    public class CatagoryController : Controller
    {
        [HttpGet]
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Catagory(int Id)
        {
            WebShopContext context = HttpContext.RequestServices.GetService(typeof(WebShopContext)) as WebShopContext;
            ViewBag.catagory = context.getCatagoryFromId(Id);
            ViewBag.Products = context.getProductsInCatagory(Id);
            return View();
        }
    }
        
}

WebShop/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Mvc;

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@inject WebShopContext context

@{
    var catagories = context.GetAllCatagories();
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebShop</title>

    <environment names="Development">
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/reactstrap/7.1.0/reactstrap.full.js"></script>
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <link href="~/lib/bootstrap/dist/css/bootstrap-theme.css" rel="stylesheet" />
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-grid.css" />
        <link href="~/lib/bootstrap/dist/css/bootstrap-grid.css" rel="stylesheet" />
        <script src="~/lib/popper.js/dist/umd/popper.js"></script>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

        <link href="~/css/Grid.css" rel="stylesheet" />
    </environment>

    <environment names="Staging,Production">
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>

        <script src="~/lib/popper.js/dist/umd/popper.js"></script>
        <script src="~/lib/vue/dist/vue.js"></script>



        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/reactstrap/7.1.0/reactstrap.full.js"></script>
    </environment>


</head>
<body >

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Erik's Webshop</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">

                <li class="nav-item">
                    <a class="nav-link" asp-controller="ShoppingCart" asp-action="Index">
                <i class="fas fa-shopping-cart"></i> Shopping cart
                <span class="badge badge-light"> 5 </span>
                <span class="sr-only">(current)</span>
                </a>
                </li>



                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-list"></i> catagories
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        @foreach (Catagory catagory in catagories)
            {
                <a class="dropdown-item" asp-controller="Catagory" asp-action="Catagory" asp-route-id="@catagory.Id">@catagory.Name</a>
}
                    </div>
                </li>

                @if (!SignInManager.IsSignedIn(User) || SignInManager.IsSignedIn(User) && SignInManager.UserManager.SupportsUserRole.ToString() != "Admin")
    {
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-user"></i> User Management
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" asp-action="">User Profile</a>
                    <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">Logout</a>
                    <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Register">Register</a>
                    <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Login">Login</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
}

            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>

    @*<partial name="_CookieConsentPartial" />*@
    </br>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - WebShop</p>
        </footer>
    </div>

    @RenderSection("Scripts", required: false)

</body>
</html>

WebShop/Views/Shared/_ProductInsert.cshtml
<div>
    @{ var teller = 0;

        foreach (Product product in ViewBag.Products)
        {

            if (teller == 0)
            {
                @:<div class="row">
}

<div class="col-sm-4 col-md-4">
    <div class="mb-4 shadow-sm">

        <div class="card shadow" style="width:100%; box-shadow:10px">
            <img class="card-img-top img-fluid" src="@product.ImagePath" alt="Card image Responsive image" style="height:300px">
            <div class="card-body">
                <h6 class="card-title text-wrap text-truncate" style="height: 35px;"><b>@product.Title</b></h6>
                <div class="text-wrap text-truncate" style="height:150px">
                    <p class="card-text"><i>@product.Description</i></p>
                </div>
                <div class="clearfix">
                    <div class="btn-group float-right">
                        <a class="btn btn-sm  btn-danger" href="#"><i class="fas fa-cart-arrow-down"></i></a>
                        <a class="btn btn-sm  btn-success" asp-controller="ShoppingCart" asp-action="Buy" asp-route-id="@product.Id">Add to cart</a>
                    </div>
                </div>

                </div>
            </div>
    </div>
</div>




    teller++;
    @if (teller == 3)
    {
        teller = 0;
    @:  </div>
}

    }
    }
</div>